services:
  - type: web
    name: chatgpt-flask-app
    env: python
    runtime: python-3.12.2
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
    nodeVersion: 20.12.2
